/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

/**
 *
 * @author pc
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbToList = new javax.swing.JLabel();
        lbToModify = new javax.swing.JLabel();
        lbToAdd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÍ THƯ VIỆN:");

        lbToList.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbToList.setForeground(new java.awt.Color(0, 204, 255));
        lbToList.setText("Danh sách sách hiện có");
        lbToList.setToolTipText("Click vào!!");
        lbToList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbToList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbToListMouseClicked(evt);
            }
        });

        lbToModify.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbToModify.setForeground(new java.awt.Color(0, 204, 255));
        lbToModify.setText("Chỉnh sửa thông tin sách");
        lbToModify.setToolTipText("Click vào!!");
        lbToModify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbToModify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbToModifyMouseClicked(evt);
            }
        });

        lbToAdd.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbToAdd.setForeground(new java.awt.Color(0, 204, 255));
        lbToAdd.setText("Thêm mới sách");
        lbToAdd.setToolTipText("Click vào!!");
        lbToAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbToAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbToAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                    .addComponent(lbToModify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbToList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbToAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbToList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbToModify)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbToAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbToListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbToListMouseClicked
        this.dispose();
        new ListBookFrame().setVisible(true);
    }//GEN-LAST:event_lbToListMouseClicked

    private void lbToModifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbToModifyMouseClicked
        this.dispose();
        new ModifyBookFrame().setVisible(true);
    }//GEN-LAST:event_lbToModifyMouseClicked

    private void lbToAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbToAddMouseClicked
        this.dispose();
        new AddBookFrame().setVisible(true);
    }//GEN-LAST:event_lbToAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbToAdd;
    private javax.swing.JLabel lbToList;
    private javax.swing.JLabel lbToModify;
    // End of variables declaration//GEN-END:variables
}
